### ISSUE TITLE
False-negative cuddled assignment line above

### ISSUE THREAD

**Issue by utdrmac** [bombsimon/wsl#106]
My code:
```
	// Network constants
	networkConstants := bc.Current.CurrentConstants()
	log.WithFields(log.Fields{
		"PreservedCycles":       networkConstants.PreservedCycles,
		"BlocksPerCycle":        networkConstants.BlocksPerCycle,
		"BlocksPerRollSnapshot": networkConstants.BlocksPerRollSnapshot,
		"BlocksPerCommitment":   networkConstants.BlocksPerCommitment,
	}).Debug("Loaded Network Constants")
```

Linter error:
```
tribbles.go:61:2:only cuddled expressions if assigning variable or using from line above (wsl)
	log.WithFields(log.Fields{
```

As you can see, I am absolutely using the assigned variable from the line above. Not sure how to ignore this.

**Comment by bombsimon** [comment]
Thanks for the report! Surprised I've not stumbled upon this earlier, we should definitely check the full following statement and not just the line immediately after assigning to see if it's used.

PRs welcome, will try to look at this too but might be a couple of days away.

**Comment by bombsimon** [comment]
Sorry this took a while but this should now be fixed in wsl, will be a part of `golangci-lint` next time it's updated.
