### ISSUE TITLE
Drop overlapping support for v4

### ISSUE THREAD

**Issue by bombsimon** [bombsimon/wsl#110]
This linter has been in a maintenance like mode for a while and never got the fixer implemented. One of the reasons the fixer never got added was that I had issues getting some of the rules to work properly. Both grouping of `const`/`var` and also due to comments.

Since this linter was created we now have [gofumpt](https://github.com/mvdan/gofumpt) which addresses (and fixes!) a lot of the issues `wsl` reports on. There's also [whitespace](https://github.com/ultraware/whitespace) which only focuses on the empty lines in the start and end of a function. This linter too has support for suggested fixes. Lastly we have [nlreturn](https://github.com/ssgreg/nlreturn) which checks if your return statement has a preceding newline and can fix that.

So, to actually make this linter more resonable to use (less opinionated and more focused) and also make it easier to finally add a fixer, which I think is really important to make it useful, I want to drop support for all overlapping features and point anyone in need of those to the other alternatives listed above. This would mean that a lot of the rules `wsl` warns about would be removed. I also think it may help to make the error reporting more generic (similar to how _"File is not `gofumpt`-ed"_).

I don't really have a plan for when to start on this but I'm writing this down to make it visible.

**Comment by jtagcat** [comment]
As far as gofumpt goes, I support; but for whitespace and nlreturn, it's meh to have 10 wsl functions as 10 separate projects (without any advancities).

**Comment by bombsimon** [comment]
> As far as gofumpt goes, I support; but for whitespace and nlreturn, it's meh to have 10 wsl functions as 10 separate projects (without any advancities).

Thanks for your feedback! Yeah, you might be right. Whitespaces and return are both related to empty lines rather than styling so I might try to keep them! For whitespaces I think I'll just be less strict with comments and allow either a comment or a statement, right now the comment parsing code is unnecessary complex just to catch all kind of patterns.

**Comment by bombsimon** [comment]
Due to the progress in #72 this issue now only addresses changes that's not simply adding or removing a whitespace. This is any kind of reordering (which isn't really a thing but noted as a suggested fix) and grouping of `var`/`const`

**Comment by bombsimon** [comment]
Closing this since the only thing left is `var` grouping which can be allowed in `wsl` if we want to avoid conflicting report.
