### ISSUE TITLE
[Docs] `force-err-cuddling` is referenced as `enforce-err-cuddling` in the documentation

### ISSUE THREAD

**Issue by AndreiBarbuOz** [bombsimon/wsl#113]
the golangci reference documentation is using the correct key: https://github.com/golangci/golangci-lint/blob/4b218e664c8488364a1ebc001c07949073e2d611/.golangci.reference.yml#L1785

but the wsl documentation is using what I presume to be the old version of the flag: https://github.com/bombsimon/wsl/blob/master/doc/configuration.md#enforce-err-cuddling

**Comment by bombsimon** [comment]
Nice find! [force-err-cuddling](https://github.com/bombsimon/wsl/blob/d6446b9deffa67287c4b747a88f35109dc723197/cmd/wsl/main.go#L40) is the right flag. PRs welcome.

**Comment by gandarez** [comment]
Somehow it has changed back to `enforce...` so I did another PR to get it fized as well the assignment for few properties missed.
https://github.com/golangci/golangci-lint/pull/3407
