### ISSUE TITLE
`--fix` ?

### ISSUE THREAD

**Issue by mryanprice** [bombsimon/wsl#131]
In the README, I saw an example usage of:

```
wsl --allow-cuddle-declarations --fix ./...
```

and a note "This linter provides a fixer that can fix most issues with the --fix flag. "

However, when I try to use `--fix` it doesn't seem to do anything, and the usage message doesn't include `--fix`.  Hopefully I am doing something silly/wrong...

```
$ wsl
xxx/yyy/zzz_v1.go:64: ranges should only be cuddled with assignments used in the iteration
$ wsl --fix
flag provided but not defined: -fix
Usage of wsl:
  -allow-assign-and-call
    	Allow assignments and calls to be cuddled (if using same variable/type) (default true)
  -allow-cuddle-declarations
    	Allow declarations to be cuddled
  -allow-multi-line-assign
    	Allow cuddling with multi line assignments (default true)
  -allow-trailing-comment
    	Allow blocks to end with a comment
  -force-case-trailing-whitespace int
    	Force newlines for case blocks > this number.
  -h	Show this help text
  -help
    	
  -n	Don't lint test files
  -no-test
    	
  -strict-append
    	Strict rules for append (default true)
  -w	Show warnings (ignored rules)
  -warnings
```

(I did try the precise command from the README `wsl --allow-cuddle-declarations --fix ./...` and get the same error `flag provided but not defined: -fix`)

**Comment by bombsimon** [comment]
Hey!

Did you see my comment in #129? I think you installed a v1 version by mistake and thus the `--fix` flag is not available. 

Try running this (note `master` and not `latest` tag) to install the latest version:

```sh
go install github.com/bombsimon/wsl/v4/cmd...@master
```

You can confirm you have the latest version by running `wsl --help` and it should show you the `--fix` flag in the output.

**Comment by mryanprice** [comment]
> Hey!
> 
> Did you see my comment in #129? I think you installed a v1 version by mistake and thus the `--fix` flag is not available.
> 
> Try running this (note `master` and not `latest` tag) to install the latest version:
> 
> ```shell
> go install github.com/bombsimon/wsl/v4/cmd...@master
> ```
> 
> You can confirm you have the latest version by running `wsl --help` and it should show you the `--fix` flag in the output.

That does work!  Sorry for making you repeat yourself.  Thanks again!
