### ISSUE TITLE
Allow cuddled return for variable just declared

### ISSUE THREAD

**Issue by mitar** [bombsimon/wsl#137]
I have a function which ends like:

```
        n := 10
        
	_, err = w.buf.WriteTo(w.out)
	return n, err
```

and I get the "return statements should not be cuddled if block has more than two lines" error. But I think this one should not require a newline. This is to me similar to:

```
	_, err = w.buf.WriteTo(w.out)
        if err != nil {
        	return n, err
        }

	return n, nil
```

Only that it combines those two together into one line. So I think no newline should be required here.

**Comment by bombsimon** [comment]
The rule is not really a part of the semantics of the code but the cognitive complexity and split of control flow like `return`, `continue` and `break` in code blocks that spans over more than just one or two lines. The philosophy is the same as in [`nlreturn`](https://github.com/ssgreg/nlreturn). 

This linter would suggest to do:

```go
{
    n := 10
    _, err = w.buf.WriteTo(w.out)

    return n, err
}
```

It seems somewhat related to #112. As of now I don't plan to add support to skip the empty line for specific cases like this.
