### ISSUE TITLE
Multiline assignments disallow for if statement to follow

### ISSUE THREAD

**Issue by ajpetersons** [bombsimon/wsl#22]
Sometimes assignments (function call results) may be split into multiple lines in order to avoid too long lines. In case such statements are used, linter does not allow an `if` statement to follow. Since the `if` statement is closely related to the operation, it should still be allowed for the `if` to follow an assignment that is split into multiple lines.

Allowed:
```go
err := functionCall(arg1, arg2)
if err != nil {
    return err
}
```

Not allowed:
```go
err := functionCall(
    arg1, arg2,
)
if err != nil {
    return err
}
```

**Comment by bombsimon** [comment]
I'll look into this! I think I'll make this configurable since the latest release have better support for configuration. I agree that this is so closely related that the default behaviour should be to allow this!

**Comment by bombsimon** [comment]
@ajpetersons Ooops, auto closed this from the commit! Although this should now be fixed and the default behaviour. Created a new release with this change as well [`v1.2.0`](https://github.com/bombsimon/wsl/releases/tag/v1.2.0).

Can you see if this is more in line with what you had in mind?

Thanks for the report and feedback!

**Comment by ajpetersons** [comment]
Looks good, thanks!
