### ISSUE TITLE
False-positive "if statements should only be cuddled with assignments used in the if statement itself"

### ISSUE THREAD

**Issue by zx8** [bombsimon/wsl#26]
What exactly does this check want me to change, or is this a false-positive?

Repro:
```go
foo := bar.Baz(foobar)
if t, ok := data[foo]; ok {
  data["hello."+foo] = t
  delete(data, foo)
}
```

**Comment by bombsimon** [comment]
Thanks for your report! That’s a false positive that should be allowed! I’ll look into this!
