### ISSUE TITLE
Correct Example syntax triggering "block should not end with a whitespace (or comment)"

### ISSUE THREAD

**Issue by hairyhenderson** [bombsimon/wsl#38]
[Example](https://golang.org/pkg/testing/#hdr-Examples) functions must end with comments, but wsl doesn't like that very much:

Here's a snippet that's failing for me in [go-which](https://github.com/hairyhenderson/go-which):

```go
func ExampleWhich() {
        path := Which("sh")
        fmt.Printf("Found sh at: %s", path)

        // Output: Found sh at: /bin/sh
}
```

```console
$ wsl which_test.go 
which_test.go:124: block should not end with a whitespace (or comment)
```

I'm thinking wsl should probably ignore this particular check in `Example` tests.

**Comment by hairyhenderson** [comment]
Another thing to note: I'm using golangci-lint to run wsl, and so I _could_ add `// nolint: wsl` to ignore these failures. However, that comment then gets put into the godoc:

<img width="653" alt="Screen Shot 2019-10-14 at 10 50 38" src="https://user-images.githubusercontent.com/2037086/66760677-97adac00-ee70-11e9-99b1-2d327f446afa.png">

**Comment by bombsimon** [comment]
Thank you for this report! I'll look into this asap!

**Comment by hairyhenderson** [comment]
@bombsimon I hacked up a fix which I'll PR soon, though it's a bit messy 😉

**Comment by hairyhenderson** [comment]
See #39 for a potential fix

**Comment by bombsimon** [comment]
Looks good! Thank you so much for the report and the PR! Merged and I'll try to include it in an existing PR to update `golangci-lint`!
