### ISSUE TITLE
Allow trailing whitespace in blocks

### ISSUE THREAD

**Issue by marcel-aan-zee** [bombsimon/wsl#43]
I see some options like --no-test -allow-declaration, but I'm uncertain what they do.
I was looking for a way to disable some of the warnings about the:
block should not start/end with a whitespace
but I'm not sure if there is any such option

**Comment by bombsimon** [comment]
Thanks for the report! I've just merged a major improvement to the documentations explaining the rules, however they do not mention the flags in detail.

I'll try to look at an improvement to the flags (with examples) and even further improve the documentation under [/doc](https://github.com/bombsimon/wsl/tree/master/doc).

Regarding "block should not start/end with a whitespace", it's currently not possible to disable that warning. It seems like [ultraware/whitespace](https://github.com/ultraware/whitespace) takes the same approach as me and I just read yesterday about this being discouraged. 

Do you think it **should** be possible to start/end with a whitespace? Can you provide an example?

**Comment by marcel-aan-zee** [comment]
I love the tool btw!
Sometimes we have code that ends with a line that is not in use, so they made a comment of it.
Perhaps later, they will use it at that exact location. So The comment needs to be there. And it's not a mistake. Not all comments are exaplanations (for documentation purposes) ones ;-)

The whitespace at the beginning is just a matter of taste. The code doesn't feel disconnected to me, since it still is inside a function. So for me, an option to configure it will be to the users of your tool to decide it's stricktness.

**Comment by bombsimon** [comment]
I think there's cases where a trailing comment might be appropriate (even if it's not for documentation purposes) and I'm open to having that configurable. I think I have to do some more research before allowing (to configure) the plain whitespace, start or end of block.

In fact, the first version of this linter only checked for leading whitespaces in a block and I came up with the idea after working with a colleague who wasn't consistent in the whitespace usage. :)

So I thik this:

```go
[token] {
    fmt.Println("x")
    // TODO: I'll add this later
}
```

Should be allowed, but not this:

```go
[token] {
    fmt.Println("x")

}
```

Or this:

```go
[token] {
    fmt.Println("x")

    // TODO: I'll add this later
}
```

To improve readability, the last example could be resolved like this:

```go
[token] {
    fmt.Println("x")
    //
    // TODO: I'll add this later
}
```

**Comment by marcel-aan-zee** [comment]
hmm. looks like you're on the right track, however, what if the  fmt.Println("x") was something different?
an if statement. Then the comment shouldn't be cuddled if it wasn't a comment.
Anyway: a better solution for the edge cases !

**Comment by bombsimon** [comment]
Yeah, all statements should be allowed with the idea I have in mind, even this one:

```go
token {
    if true {
        defer go func() {
            fmt.Println("x")
            // I'm allowed!
        }
    }
    //
    // Me too!
}
```

**Comment by bombsimon** [comment]
Btw, I didn't forget the original titel and already had in mind to improve the documentation further so that will be fixed too!

**Comment by marcel-aan-zee** [comment]
I keep watching you ;-)

**Comment by bombsimon** [comment]
@marcel-aan-zee I've added support to allow trailing comments with flag `--allow-trailing-comment`. You have to build it yourself from the master branch since I've not yet created a release.

Also there's a new issue to follow regarding the documentation, see #44.

Please let me know if there's any issues with the trailing comments!

**Comment by bombsimon** [comment]
@marcel-aan-zee I've now also merged an update to the documentation with simplified examples and added a cross reference to the available configuration to understand what it controls. It can be found in the [configuration documentation](https://github.com/bombsimon/wsl/blob/master/doc/configuration.md).
