### ISSUE TITLE
unexpected "block should not start with a whitespace (wsl)"

### ISSUE THREAD

**Issue by andig** [bombsimon/wsl#58]
Will be triggered by the comment in 

```
func NewABBProducer() Producer {
	/***
	 * http://datenblatt.stark-elektronik.de/Energiezaehler_B-Serie_Handbuch.pdf
	 */
	ops := Opcodes{
...
```

Not sure this is expected?

**Comment by bombsimon** [comment]
Thanks for the report! This is a bug and I’ll look into this!

I have been doing some work with `wsl` and comments that’s not yet merged to golangci-lint. Hopefully this is one of those and if so I’ll add a PR this weekend!

**Comment by bombsimon** [comment]
[PR](https://github.com/golangci/golangci-lint/pull/851) in `golangci-lint` to get this fix merged.

**Comment by bombsimon** [comment]
Merged to master i golangci-lint, closing
