### ISSUE TITLE
Support Output comment last in ExampleTestFunctions

### ISSUE THREAD

**Issue by suki-fredrik** [bombsimon/wsl#64]
According to https://blog.golang.org/examples `ExampleXxx` tests should end with:

```
<empty line>
    // Output:
    // <expected output>
}
```

It would be nice to update the `Block should not end with a whitespace (or comment)` rule to honor this style.

**Comment by suki-fredrik** [comment]
When looking into the code it seems it already has such support, but I still get a `wsl` error on proprietary code that looks like this:

```
func ExampleStructName_ExportedFunction() {
   var mySlice := []string{"", ...}

   for _, s := range mySlice {
      // the test
   }

   // Output:
   // input string: ""    | output value: ...
   // input string: ""    | output value: ...
}
```
The complaint is:
```
....: block should not end with a whitespace (or comment) (wsl)
}
^
```

**Comment by suki-fredrik** [comment]
```
golangci-lint has version 1.20.1 built from 849044b on 2019-10-15T19:11:27Z
```

**Comment by suki-fredrik** [comment]
re-installed using `brew install golangci/tap/golangci-lint` now issue has been fixed. Thank you!

**Comment by bombsimon** [comment]
Thank you for the report! Glad you solved this! Please add a new issue if you find any other errors!
