### ISSUE TITLE
Add a flag to allow blocks to start with a comment

### ISSUE THREAD

**Issue by ajpetersons** [bombsimon/wsl#73]
Hi! 

I see that there exists a `allow-trailing-comment` flag to allow blocks to end with a comment. We would like to have a similar flag that would allow blocks to start with comments. 

Here is our use case: we are working on an API and we use https://github.com/go-swagger/go-swagger to generate swagger documentation for our API. The syntax that all routes are defined for the doc is a comment starting with `swagger: route` and we usually place the handler description right at the start of our handler functions. This does trigger an error (we are using `golangci-lint`) and we would like to allow such comments instead of applying `nolint: wsl` to the whole handler function.

**Comment by bombsimon** [comment]
Hi! Thanks for your suggestion! Could you provide an example where this is not working? By default you should be able to have leading comments in the beginning of blocks.

`cat wsl_test.go`

```go
package main

func someBlock() int {
        // This is allowed as long as the
        // First assignment is cuddled with the comments.
        return 1
}

func aCase() int {
        switch 1 > 2 {
        case true:
                // This should be allowed, just like above.
                return 1
        default:
                // This too!
                return -1
        }
}

func multiline() int {
        /*
           Even this should be

           No Problem

           At all
        */
        return 1
}
```

```sh
$ golangci-lint run wsl_testing.go --no-config --disable-all --enable wsl && echo $?
0
```

**Comment by ajpetersons** [comment]
We were all fine while we had only one swagger specification for each function. Now due to some updates we are going to use same handlers to serve different routes that both should be present in swagger doc. Thus we have 2 swagger specifications at the start of a handler and in order for them to be parsed properly they need to be separated by an empty line.

```go
func handler(w http.ResponseWriter, r *http.Request) {
    // swagger:route POST /path/one/ 

    // swagger:route POST /path/two/
    w.WriteHeader(http.StatusOK) 
}
```

**Comment by bombsimon** [comment]
Oh, I see! Thank you!

Are you parsing the AST to find the comments? If so, they'll be in a separate list entry even if there's no whitespace: [see example](https://play.golang.org/p/W76R2vps2n9). And if you don't want to do it like that, you could and an empty comment line [like this](https://play.golang.org/p/RY15mfe8028). And I shouldn't even propose this I guess but... [this](https://play.golang.org/p/2OK7AZFuK1O) might be a way to solve it as well.

Of course, all this depends on whether you use AST parsing or not. Either way to keep own the configurations and avoid "abuse", I think the first alternative (with and empty line) would be preferred.

How do you feel about these alternatives? Do you still find a proper use case to allow leading whitesapces? If so, is all of these valid with such configuration?

```go
func one() int {
    // Hello

    // World
    return 1
}
```

```go
func one() int {
    // Hello
    // World

    return 1
}
```

```go
func one() int {

    // Hello
    // World
    return 1
}
```

**Comment by ajpetersons** [comment]
The bigger problem in this case would be that I am not doing the parsing myself, but Go-swagger (https://github.com/go-swagger/go-swagger) is. We've tried having the comments one after the other, empty comment line and other options that we could come up and neither worked. Go-swagger parses continuous comment lines as description for the route (possible responses, security rules, etc.) so we need an empty line to separate the route descriptions.

For us the only valid configuration that we see is 
```go
func one() int {
    // Hello

    // World
    return 1
}
```

We also did try to add these swagger comments to exclude rules in golangci-lint, but could not come up with a valid regular expression to achieve what we need.

**Comment by bombsimon** [comment]
Gotcha! For some reason I was thinking in terms of the issue being the `go-swagger` bot I now realise it's for the users of said package and thus nothing much you can do.

I'm leaning towards just allowing that kind of comment as is since it doesn't have a whitespace immediate after the block declaration and it doesn't have a whitespace before the first statement. Any feedback regarding sensible defaults are welcome!

**Comment by ajpetersons** [comment]
For us allowing such comments (or comments followed by a newline) at the start of blocks would work perfectly as the default behavior. I think it would make sense to have that behavior in general as the comment at the start of the function might be some `TODO` comment that is unrelated to the code following it.

**Comment by bombsimon** [comment]
@ajpetersons I've merged a fix to master but not yet updated `golangci-lint`. I also decided to not make this default so it's toggled of by default.

I've not made any updates to `golangci-lint` yet but I probably should since #65 isn't in `golangci-lint` yet either. If you feel comfortable building `golangci-lint` from master feel free, otherwise I'll do this when I've got some time.

**Comment by ajpetersons** [comment]
Thanks! 

Having the feature not enabled by default will not be an issue for us, we will update the configuration files.

**Comment by bombsimon** [comment]
[PR in `golangci-lint`](https://github.com/golangci/golangci-lint/pull/982). Will close this issue when merged.

**Comment by bombsimon** [comment]
Merged to master in golangci-lint, will be in next release.
