### ISSUE TITLE
Add rule to cuddle the err assignation with the if check

### ISSUE THREAD

**Issue by dcu** [bombsimon/wsl#77]
In the current version this is ok:

```go
a := 1
err := foo()

if err != nil {
    return err
}
```

I think it'd be better if the err checking is ALWAYS close to the err assignation like:

```go
a := 1

err := foo()
if err != nil {
    return err
}
```

both examples are accepted by wsl but my suggestion is to add a rule to reject the first example. what do you think?

**Comment by bombsimon** [comment]
Thanks for the issue!

This is configurable to enforce, see [--force-err-cuddling](https://github.com/bombsimon/wsl/blob/master/doc/configuration.md#enforce-err-cuddling). You can apply that in `wsl` or `golangci-lint` and it will enforce assignments to `err` to be cuddled with `if err...` statements.

**Comment by dcu** [comment]
awesome, thanks

**Comment by dcu** [comment]
it didn't work:

```
> wsl -allow-assign-and-call -allow-cuddle-declarations -force-err-cuddling ./shared/...
flag provided but not defined: -force-err-cuddling
Usage of /Users/dcuadrado/go/bin/wsl:
  -allow-assign-and-call
    	Allow assignments and calls to be cuddled (if using same variable/type) (default true)
  -allow-cuddle-declarations
    	Allow declarations to be cuddled
  -allow-multi-line-assign
    	Allow cuddling with multi line assignments (default true)
  -allow-trailing-comment
    	Allow blocks to end with a comment
  -force-case-trailing-whitespace int
    	Force newlines for case blocks > this number.
  -h	Show this help text
  -help
```

**Comment by bombsimon** [comment]
What version of WSL are you using? Try installing the latest with something like

```sh
GO111MODULE=off go get -u github.com/bombsimon/wsl/...
```

Or your preferred way. The flag you're lacking seems to be missing from your version but is present in version 3.0:

```sh
$ wsl --help 2>&1 | grep -A1 'force-err-cuddling'
  -force-err-cuddling
        Force cuddling of error checks with error var assignment
```

**Comment by bombsimon** [comment]
For reference, see original issue #65

**Comment by dcu** [comment]
thanks that worked, yes indeed it was using modules
